<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="bunit" Version="2.9.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="EggIdentity.AdminUi" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.Auth" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.Bot" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.Bot.AdminUi" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.Client" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.CodeStyle" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.Contract" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.Db" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.Fallback" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.Filtering" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.Metrics" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.Metrics.AdminUi" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.Styles" Version="2.2.9" />
    <PackageVersion Include="EggIdentity.UI" Version="2.2.9" />
    <PackageVersion Include="EggIncognito.Protos" Version="2.10.0" />
    <PackageVersion Include="Markdig" Version="0.41.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="MonorailCss" Version="0.1.3" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Photino.Blazor" Version="4.0.13" />
    <PackageVersion Include="protobuf-net" Version="3.2.45" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageVersion Include="Xunit.SkippableFact" Version="1.5.23" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
