CREATE TABLE IF NOT EXISTS el_mission_fuel (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    UUID    NOT NULL,
    mission_id TEXT    NOT NULL,
    player_id  TEXT    NOT NULL,
    fuel_index BIGINT  NOT NULL,
    egg_id     BIGINT  NOT NULL,
    amount     DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (user_id, mission_id, player_id, fuel_index)
);
CREATE INDEX IF NOT EXISTS idx_el_mission_fuel_user_player ON el_mission_fuel(user_id, player_id);